#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "swingmusic"
name = "Swing Music"
description.en = "Beautiful music player for your local audio files"
description.fr = "Magnifique lecteur de musique pour vos fichiers audios locaux"

version = "2.1.3~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://swingmx.com/"
admindoc = "https://swingmx.com/guide/getting-started.html"
code = "https://github.com/swingmx/swingmusic"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "10M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/orhtej2/swingmusic/releases/download/v2.1.3/swingmusic_linux_x86_64"
    amd64.sha256 = "cf3f5afc5b032b4ccd727c3a07b3178fcf90699000ffe50b9bfff3316c7606a6"

    arm64.url = "https://github.com/orhtej2/swingmusic/releases/download/v2.1.3/swingmusic_linux_aarch64"
    arm64.sha256 = "943e9b1d4c6d6d7c5916ad096cacda464a377b1601c8466c193899f0655a38fe"

    extract = false
    rename = "swingmusic"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "swingmusic_linux_x86_64$"
    autoupdate.asset.arm64 = "swingmusic_linux_aarch64$"
    autoupdate.upstream = "https://github.com/orhtej2/swingmusic"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ["ffmpeg", "libavcodec-extra",]
