#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "swingmusic"
name = "Swing Music"
description.en = "Beautiful music player for your local audio files"
description.fr = "Magnifique lecteur de musique pour vos fichiers audios locaux"

version = "3.0.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://swingmx.com/"
admindoc = "https://swingmx.com/guide/getting-started.html"
code = "https://github.com/swingmx/swingmusic"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "10M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/swingmx/swingmusic/releases/download/v3.0.0/swingmusic_linux_x86_64"
    amd64.sha256 = "86f0e3a4bd103bd9cd96d3a97261fd22060c61d90bea80afa6cae8157defbe03"

    arm64.url = "https://github.com/swingmx/swingmusic/releases/download/v3.0.0/swingmusic_linux_aarch64"
    arm64.sha256 = "b8dadec2304b2f7c68a813725b7a6496066d420fd4b9f9bcca3d5148551d1c27"

    extract = false
    rename = "swingmusic"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "swingmusic_linux_x86_64$"
    autoupdate.asset.arm64 = "swingmusic_linux_aarch64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ["ffmpeg", "libavcodec-extra",]
