#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "swingmusic"
name = "Swing Music"
description.en = "Beautiful music player for your local audio files"
description.fr = "Magnifique lecteur de musique pour vos fichiers audios locaux"

version = "2.1.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://swingmx.com/"
admindoc = "https://swingmx.com/guide/getting-started.html"
code = "https://github.com/swingmx/swingmusic"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "10M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/swingmx/swingmusic/releases/download/v2.1.0/swingmusic_linux_x86_64"
    amd64.sha256 = "32800344b6206e950ea29350413ab864850f8c34e7a12f28c561e375ad04a097"

    arm64.url = "https://github.com/swingmx/swingmusic/releases/download/v2.1.0/swingmusic_linux_aarch64"
    arm64.sha256 = "df0bb44143e83bf444ad54c1d052dd77f98606bae010ca0a796b63d00d63207b"

    extract = false
    rename = "swingmusic"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "swingmusic_linux_x86_64$"
    autoupdate.asset.arm64 = "swingmusic_linux_aarch64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ["ffmpeg", "libavcodec-extra",]
